### ISSUE TITLE
Projeto Voluntário - CRUD

### ISSUE THREAD

**Issue by santosvini** [fernandoleonid/speed-code-css-html#2]
Olá Professor, aprendendo muito também com seu conteúdo e fazendo desde o começo, primeira vez que faço um CRUD, abro essa issue, para saber se posso usar para um projeto voluntário? 

Farei outras pages também, mas fica aqui meu questionamento, sobre essa utilização.

Abs e obrigado por ensinar

**Comment by fernandoleonid** [comment]
Pode usar, depois me passa o link do projeto, ou me marca.
